services:
  postgres:
    image: postgres:16
    container_name: store-crm-postgres
    environment:
      POSTGRES_DB: store_crm_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - store_crm_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d store_crm_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: lgs-store-crm:v2.1-multitenancy-fix
    container_name: store-crm-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  store_crm_pgdata: