apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: store-crm
type: Opaque
stringData:
  POSTGRES_USER: your_postgres_username_here
  POSTGRES_PASSWORD: your_postgres_password_here