apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: store-crm
type: Opaque
stringData:
  RABBITMQ_USERNAME: your_rabbitmq_username_here
  RABBITMQ_PASSWORD: your_rabbitmq_password_here